name: Update President Polls and Build Web App

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download president_polls.csv
      run: curl -o data/president_polls.csv https://projects.fivethirtyeight.com/polls/data/president_polls.csv

    - name: Run model.py
      run: python model.py

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Node.js dependencies
      run: |
        cd web-app
        npm ci

    - name: Build web app
      run: |
        cd web-app
        npm run build

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update president_polls.csv, run model.py, and build web app"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}